
ALTER TABLE public.quiz_scores 
ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
ADD COLUMN IF NOT EXISTS question_index INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS time_taken_seconds NUMERIC NOT NULL DEFAULT 0;
